name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - uses: pre-commit/action@v3.0.1
